{
 "title": "Grafana",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alert Execution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(labels->>'pod', ' - ', labels->>'quantile') AS metric,\n  $__timeGroup(time, '$__interval') AS time,\n  MAX(value) AS value\nFROM metrics\nWHERE $__timeFilter(time) AND name = 'grafana_alerting_execution_time_milliseconds'\nGROUP BY $__timeGroup(time, '$__interval'), metric\nORDER BY $__timeGroup(time, '$__interval'), metric"
    }
   ]
  },
  {
   "title": "Alerts Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  metric,\n  bucket AS time,\n  rate_time(value, lag(value) OVER w, '$__interval') AS value\nFROM (\nSELECT\n  CONCAT(labels->>'pod', ' - ', labels->>'type') AS metric,\n  $__timeGroup(time, '$__interval') AS bucket,\n  MAX(value) AS value\nFROM metrics\nWHERE $__timeFilter(time) AND name = 'grafana_alerting_notification_failed_total'\nGROUP BY metric, bucket\n) AS m\nWINDOW w AS (PARTITION BY metric ORDER BY bucket)\nORDER BY bucket, metric"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  metric,\n  bucket AS time,\n  rate_time(value, lag(value) OVER w, '$__interval') AS value\nFROM (\nSELECT\n  CONCAT(labels->>'pod', ' - ', labels->>'state') AS metric,\n  $__timeGroup(time, '$__interval') AS bucket,\n  MAX(value) AS value\nFROM metrics\nWHERE $__timeFilter(time) AND name = 'grafana_alerting_result_total'\nGROUP BY metric, bucket\n) AS m\nWINDOW w AS (PARTITION BY metric ORDER BY bucket)\nORDER BY bucket, metric"
    }
   ]
  },
  {
   "title": "Alert Execution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(labels->>'pod', ' - ', labels->>'state') AS metric,\n  $__timeGroup(bucket, '$__interval') AS time,\n  SUM(delta_value) AS value\nFROM agg_grafana_alert AS s \nJOIN metric_labels AS l \n  ON l.lid = s.lid\nWHERE $__timeFilter(bucket)\nGROUP BY $__timeGroup(bucket, '$__interval'), metric\nORDER BY $__timeGroup(bucket, '$__interval'), metric"
    }
   ]
  }
 ]
}