{
 "title": "Hypertables",
 "description": "Overview over TimescaleDB Hypertables and their space usage",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "database", "query": "postgres" },
   {
    "name": "relation",
    "label": "Relation",
    "query": "metrics,metric_labels,metric_samples"
   }
  ]
 },
 "panels": [
  {
   "title": "PostgreSQL Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT current_setting('server_version');"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(hypertable.table_schema::text, '.', hypertable.table_name::text) AS table_name,\n  pg_size_bytes(hypertable.total_size) AS total_size,\n  pg_size_bytes(hypertable.table_size) AS table_size,\n  pg_size_bytes(hypertable.index_size) AS index_size,\n  pg_size_bytes(hypertable.toast_size) AS toast_size\nFROM \n  timescaledb_information.hypertable AS hypertable,\n  hypertable_approximate_row_count(CONCAT(hypertable.table_schema::text, '.', hypertable.table_name::text)) AS counts\nWHERE hypertable.table_size != ''\nORDER BY hypertable.index_size DESC;"
    }
   ]
  },
  {
   "title": "Space Usage Hypertables",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  CONCAT(counts.schema_name, '.', hypertable.table_name) as \"table_name\",\n  counts.row_estimate AS \"row_count\",\n  hypertable.table_size AS \"table_size\",\n  hypertable.index_size AS \"index_size\",\n  hypertable.total_size AS \"total_size\"\nFROM \n  timescaledb_information.hypertable AS hypertable,\n  hypertable_approximate_row_count(CONCAT(hypertable.table_schema::text, '.', hypertable.table_name::text)) AS counts\nWHERE hypertable.table_size != ''\nORDER BY hypertable.total_size DESC;"
    }
   ]
  },
  {
   "title": "TimescaleDB Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT extversion FROM pg_extension WHERE extname='timescaledb'"
    }
   ]
  },
  {
   "title": "Table Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(1) FROM _timescaledb_catalog.hypertable"
    }
   ]
  },
  {
   "title": "Chunk Size",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(n_live_tup) AS value,\n  to_timestamp(lower(ranges[1])/10^6) AS time\nFROM chunk_relation_size('$relation') AS m\nJOIN pg_stat_user_tables AS t\n  ON CONCAT(t.schemaname, '.', t.relname) = m.chunk_table\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Chunk Size",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "select MAX(table_name) AS metric,to_timestamp(lower(ranges[1])/10^6) AS time , SUM(total_bytes) FROM _timescaledb_catalog.hypertable,chunk_relation_size(table_name::text)WHERE hypertable.table_name LIKE 'metric%' GROUP BY time ORDER BY 1, 2;\r\n"
    }
   ]
  }
 ]
}