{
 "title": "Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Absolute Lag",
   "type": "gauge",
   "description": "time since last recorded metric",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "  SELECT\n    metrics.labels->>'pod' AS \"metric\",\n    MAX(\"time\") AS \"time\",\n    EXTRACT(EPOCH FROM NOW()) - MAX(value) AS \"value\"\n  FROM metrics\n  WHERE\n    time > NOW() - INTERVAL '15 minute'\n    AND name = 'prometheus_remote_storage_highest_timestamp_in_seconds'\n    AND value != 'NaN'\n  GROUP BY metric\n  ORDER BY time DESC\n  LIMIT 4"
    }
   ]
  },
  {
   "title": "Storage Lag",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "prometheus_remote_storage_highest_timestamp_in_seconds - on(pod) prometheus_remote_storage_queue_highest_sent_timestamp_seconds{queue=~\"0.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Samples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Samples Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  tg AS \"time\",\n  metric,\n  ((\n  CASE \n    WHEN lag(value) OVER w IS NULL THEN 0\n    WHEN value > lag(value) OVER w THEN (value - lag(value) OVER w)\n    ELSE value\n  END\n  ) / EXTRACT(EPOCH FROM INTERVAL '${__interval}')) AS \"value\"\nFROM (\nSELECT\n  labels->>'pod' AS \"metric\",\n  time_bucket('${__interval}', \"time\") AS \"tg\",\n  MAX(value) AS \"value\"\nFROM metrics\nWHERE\n  $__timeFilter(\"time\") and\n  name = 'prometheus_remote_storage_succeeded_samples_total'\nGROUP BY metric, tg\nORDER BY metric, tg\n) AS m\nWHERE value > 0\nWINDOW w AS (PARTITION BY metric ORDER BY tg)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  tg AS \"time\",\n  metric,\n  ((\n  CASE \n    WHEN lag(value) OVER w IS NULL THEN 0\n    WHEN value > lag(value) OVER w THEN (value - lag(value) OVER w)\n    ELSE value\n  END\n  ) / EXTRACT(EPOCH FROM INTERVAL '${__interval}')) AS \"value\"\nFROM (\nSELECT\n  labels->>'pod' AS \"metric\",\n  time_bucket('${__interval}', \"time\") AS \"tg\",\n  MAX(value) AS \"value\"\nFROM metrics\nWHERE\n  $__timeFilter(\"time\") and\n  name = 'adapter_samples_sent_total'\nGROUP BY metric, tg\nORDER BY metric, tg\n) AS m\nWHERE value > 0\nWINDOW w AS (PARTITION BY metric ORDER BY tg)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Storage Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  coalesce(MAX(pod), MAX(instance), 'unknown') AS \"metric\",\n  \"time\",\n  MAX(\"local\") - MAX(\"remote\") AS \"value\"\nFROM\n(\n  SELECT\n    metrics.labels->>'pod' AS \"pod\",\n    metrics.labels->>'instance' AS \"instance\",\n    $__timeGroup(\"time\", ${__interval}),\n    CASE WHEN name = 'prometheus_remote_storage_highest_timestamp_in_seconds' THEN value ELSE NULL END AS \"local\",\n    CASE WHEN name = 'prometheus_remote_storage_queue_highest_sent_timestamp_seconds' THEN value ELSE NULL END AS \"remote\"\n  FROM metrics\n  WHERE\n    $__timeFilter(\"time\")\n    AND name IN ('prometheus_remote_storage_highest_timestamp_in_seconds', 'prometheus_remote_storage_queue_highest_sent_timestamp_seconds')\n    AND value != 'NaN'\n) t\nGROUP BY time, instance\nORDER BY time, instance;"
    }
   ]
  },
  {
   "title": "Samples Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(prometheus_remote_storage_succeeded_samples_total[5m])",
     "legendFormat": "{{ pod }} - {{ queue }}"
    }
   ]
  },
  {
   "title": "Storage Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_highest_timestamp_in_seconds - on(pod) prometheus_remote_storage_queue_highest_sent_timestamp_seconds{queue=~\"0.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}