{
 "title": "Schema",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "database", "label": "Database", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Chunk Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n  MAX(table_name) AS metric,\r\n  to_timestamp(lower(ranges[1])/10^6) AS time,\r\n  SUM(total_bytes)\r\nFROM _timescaledb_catalog.hypertable, chunk_relation_size(table_name::text) \r\nWHERE \r\n  table_name LIKE 'metric%' \r\nGROUP BY time \r\nORDER BY metric, time;\r\n"
    }
   ]
  },
  {
   "title": "Compression",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  hypertable_name,\n  1 - AVG(pg_size_bytes(compressed_total_bytes)::float / pg_size_bytes(uncompressed_total_bytes)) AS compression_ratio\nFROM timescaledb_information.compressed_chunk_stats\nWHERE compression_status = 'Compressed'\nGROUP BY hypertable_name"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(pg_relation_size(C.oid)) AS \"size\"\nFROM pg_class C\nLEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)\nWHERE nspname NOT IN ('pg_catalog', 'information_schema');\n"
    }
   ]
  },
  {
   "title": "Labels Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT pg_relation_size('metric_labels') + pg_relation_size('metrics_labels')"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(hypertable.table_schema::text, '.', hypertable.table_name::text) AS table_name,\n  pg_size_bytes(hypertable.total_size) AS total_size,\n  pg_size_bytes(hypertable.table_size) AS table_size,\n  pg_size_bytes(hypertable.index_size) AS index_size,\n  pg_size_bytes(hypertable.toast_size) AS toast_size\nFROM \n  timescaledb_information.hypertable AS hypertable,\n  hypertable_approximate_row_count(CONCAT(hypertable.table_schema::text, '.', hypertable.table_name::text)) AS counts\nWHERE hypertable.table_size != ''\nORDER BY hypertable.index_size DESC;"
    }
   ]
  },
  {
   "title": "Active Conns",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(time, '$__interval') AS time, \n  labels->>'pod' AS metric, \n  MAX(value) AS value\nFROM metrics \nWHERE \n  $__timeFilter(time) AND \n  name = 'adapter_connections_used_current'\nGROUP BY $__timeGroup(time, '$__interval'), metric\nORDER BY $__timeGroup(time, '$__interval'), metric"
    }
   ]
  },
  {
   "title": "Active Labels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  metric, \n  bucket AS time, \n  rate_time(value, lag(value) OVER w, '$__interval') \nFROM (\nSELECT \n  labels->>'pod' AS metric, \n  $__timeGroup(time, '$__interval') AS bucket, \n  MAX(value) AS value\nFROM metrics \nWHERE \n  $__timeFilter(time) AND \n  name = 'adapter_labels_written_total' \nGROUP BY metric, bucket\nORDER BY metric, bucket\n) AS s \nWINDOW w AS (PARTITION BY s.metric ORDER BY s.bucket)"
    }
   ]
  },
  {
   "title": "Live Tuples",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  relname AS metric,\n  n_live_tup AS value\nFROM pg_stat_all_tables\nORDER BY n_live_tup DESC\nLIMIT 50;"
    }
   ]
  },
  {
   "title": "Open Conns",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(time, '$__interval') AS time, \n  labels->>'pod' AS metric, \n  MAX(value) AS value\nFROM metrics \nWHERE \n  $__timeFilter(time) AND \n  name = 'adapter_connections_open_current'\nGROUP BY $__timeGroup(time, '$__interval'), metric\nORDER BY $__timeGroup(time, '$__interval'), metric"
    }
   ]
  },
  {
   "title": "Label Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  labels->>'pod' AS metric,\n  time_bucket('$__interval', time) AS time,\n  MAX(value) AS value\nFROM metrics\nWHERE \n  name = 'adapter_labels_cache_current' AND \n  $__timeFilter(\"time\")\nGROUP BY time_bucket('$__interval', time), metric\nORDER BY time_bucket('$__interval', time), metric"
    }
   ]
  }
 ]
}