{
 "title": "Container Limits",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Pod CPU Limits",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(labels->>'pod', '/', labels->>'container') AS metric,\n  $__timeGroup(time, $__interval),\n  MAX(value) / 100000\nFROM metrics\nWHERE\n  $__timeFilter(time) AND \n  name = 'container_spec_cpu_quota' AND\n  labels ? 'container' AND\n  value > 0\nGROUP BY metric, time_bucket('$__interval', time)\nORDER BY metric, time_bucket('$__interval', time);"
    }
   ]
  },
  {
   "title": "Pod Memory Limits",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(labels->>'pod', '/', labels->>'container') AS metric,\n  $__timeGroup(time, $__interval),\n  MAX(value) AS value\nFROM metrics\nWHERE\n  $__timeFilter(time) AND \n  name = 'container_spec_memory_limit_bytes' AND\n  labels ? 'container' AND\n  value > 0\nGROUP BY time_bucket('$__interval', time), metric\nORDER BY time_bucket('$__interval', time), metric;"
    }
   ]
  },
  {
   "title": "Container CPU Throttling",
   "type": "graph",
   "description": "Percent of CFS shares over the last minute during which this container was throttled",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(labels->>'node', '/', labels->>'pod', '/', labels->>'container_name') AS metric, \n  time_bucket('$__interval', time) AS time, \n  MAX(value) * 1\nFROM metrics \nWHERE \n  $__timeFilter(time) AND\n  name = 'container_cpu_cfs_throttled_rate_pct' AND \n  labels ? 'container_name' AND\n  value > 0.5\nGROUP BY time_bucket('$__interval', time), metric \nORDER BY time_bucket('$__interval', time), metric;"
    }
   ]
  },
  {
   "title": "Missing Memory Limits",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(labels->>'pod', '/', labels->>'container') AS metric,\n  MAX(value) AS value\nFROM metrics\nWHERE\n  $__timeFilter(time) AND \n  name = 'container_spec_memory_limit_bytes' AND\n  labels ? 'container' AND\n  labels->>'container' NOT IN ('POD', 'helper', 'svc-0') AND\n  value = 0\nGROUP BY metric\nORDER BY metric;"
    }
   ]
  }
 ]
}