{
 "title": "Instance Alerts",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Node Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_load1",
     "rawSql": "SELECT\n  l.labels->>'nodename' AS \"metric\",\n  m.\"time\",\n  MAX(\"value\") AS \"value\"\nFROM (\n  SELECT\n    labels->>'instance' AS instance,\n    lid,\n    $__timeGroup(\"time\", $__interval),\n    value\n  FROM metrics\n  WHERE\n    $__timeFilter(\"time\") AND\n    name = 'node_load1' AND\n    value != 'NaN'\n) AS m\nJOIN metric_labels AS l\n  ON l.labels->>'__name__' = 'node_uname_info' AND\n     instance = l.labels->>'instance'\nGROUP BY metric, m.time\nORDER BY metric, m.time;"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_instance avail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_memory_MemAvailable",
     "rawSql": "-- this query relies on the node_pct prometheus rules\nSELECT\n  l.labels->>'nodename' AS \"instance\",\n  $__timeGroup(m.\"time\", $__interval),\n  MIN(m.value) AS value\nFROM metrics AS m\nJOIN metric_labels AS l\n  ON l.labels->>'__name__' = 'node_uname_info' AND \n     m.labels->>'instance' = l.labels->>'instance'\nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.name = 'node_memory_free_pct' AND\n  m.value != 'NaN'\nGROUP BY instance, m.time\nORDER BY instance, m.time;"
    }
   ]
  },
  {
   "title": "Node Root",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_instance avail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_memory_MemAvailable",
     "rawSql": "-- this query relies on the node_pct prometheus rules\nSELECT\n  l.labels->>'nodename' AS \"instance\",\n  $__timeGroup(m.\"time\", $__interval),\n  MIN(m.value) AS value\nFROM metrics AS m\nJOIN metric_labels AS l\n  ON l.labels->>'__name__' = 'node_uname_info' AND \n     m.labels->>'instance' = l.labels->>'instance'\nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.name = 'node_filesystem_free_pct' AND\n  m.value != 'NaN'\nGROUP BY instance, m.time\nORDER BY instance, m.time;"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_load1",
     "rawSql": "SELECT\n  metric,\n  time,\n  (\n    CASE\n      WHEN value >= lag(value) OVER w\n        THEN value - lag(value) OVER w\n      WHEN lag(value) OVER w IS NULL THEN NULL\n      ELSE value\n    END\n  ) / EXTRACT(epoch FROM interval '$__interval') AS \"value\"\nFROM (\n  SELECT\n    CONCAT(labels->>'instance', ' ', metrics.labels->>'device') AS \"metric\",\n    $__timeGroupAlias(\"time\", $__interval, previous),\n    MAX(value) AS \"value\"\n  FROM metrics\n  WHERE\n    $__timeFilter(\"time\")\n    AND name='node_disk_write_time_seconds_total'\n  GROUP BY metric, $__timeGroup(\"time\", $__interval)\n  ORDER BY metric, time\n) AS metrics\nWINDOW w as (PARTITION BY metric ORDER BY time)\nORDER BY metric, time;"
    }
   ]
  }
 ]
}