{
 "title": "Workloads",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "query": "postgres" }
  ]
 },
 "panels": [
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daemon Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  coalesce(MAX(apps), 'unknown') AS \"metric\",\n  time,\n  (MIN(current) / GREATEST(1, MAX(desired))) AS \"value\"\nFROM\n(\n  SELECT\n    CONCAT(labels->>'exported_namespace', '/', labels->>'daemonset') AS \"apps\",\n    \"time\" AS \"time\",\n    CASE WHEN name = 'kube_daemonset_status_current_number_scheduled' THEN value ELSE NULL END AS \"current\",\n    CASE WHEN name = 'kube_daemonset_status_desired_number_scheduled' THEN value ELSE NULL END AS \"desired\"\n  FROM metrics\n  WHERE\n    $__timeFilter(\"time\") and\n    name IN ('kube_daemonset_status_current_number_scheduled', 'kube_daemonset_status_desired_number_scheduled') and\n    value != 'NaN'\n) t\nGROUP BY apps, time\nORDER BY apps, time;"
    }
   ]
  },
  {
   "title": "Stateful Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  coalesce(MAX(apps), 'unknown') AS \"metric\",\n  time,\n  (MIN(current) / GREATEST(1, MAX(desired))) AS \"value\"\nFROM\n(\n  SELECT\n    CONCAT(labels->>'exported_namespace', '/', labels->>'statefulset') AS \"apps\",\n    \"time\" AS \"time\",\n    CASE WHEN name = 'kube_statefulset_status_replicas_ready' THEN value ELSE NULL END AS \"current\",\n    CASE WHEN name = 'kube_statefulset_status_replicas' THEN value ELSE NULL END AS \"desired\"\n  FROM metrics\n  WHERE\n    $__timeFilter(\"time\") and\n    name IN ('kube_statefulset_status_replicas_ready', 'kube_statefulset_status_replicas') and\n    value != 'NaN'\n) t\nGROUP BY apps, time\nORDER BY apps, time;"
    }
   ]
  },
  {
   "title": "Deployment Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  coalesce(MAX(apps), 'unknown') AS \"metric\",\n  time,\n  (MIN(current) / GREATEST(1, MAX(desired))) AS \"value\"\nFROM\n(\n  SELECT\n    CONCAT(labels->>'exported_namespace', '/', labels->>'deployment') AS \"apps\",\n    \"time\" AS \"time\",\n    CASE WHEN name = 'kube_deployment_status_replicas_available' THEN value ELSE NULL END AS \"current\",\n    CASE WHEN name = 'kube_deployment_status_replicas' THEN value ELSE NULL END AS \"desired\"\n  FROM metrics\n  WHERE\n    $__timeFilter(\"time\") and\n    name IN ('kube_deployment_status_replicas_available', 'kube_deployment_status_replicas') and\n    value != 'NaN'\n) t\nGROUP BY apps, time\nORDER BY apps, time;"
    }
   ]
  },
  {
   "title": "Daemon Pod Count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  coalesce(MAX(apps), 'unknown') AS \"metric\",\n  time,\n  MIN(current) AS \"value\"\nFROM\n(\n  SELECT\n    CONCAT(labels->>'exported_namespace', '/', labels->>'daemonset') AS \"apps\",\n    \"time\" AS \"time\",\n    CASE WHEN name = 'kube_daemonset_status_current_number_scheduled' THEN value ELSE NULL END AS \"current\"\n  FROM metrics\n  WHERE\n    $__timeFilter(\"time\") and\n    name = 'kube_daemonset_status_current_number_scheduled' and\n    value != 'NaN'\n) t\nGROUP BY apps, time\nORDER BY apps, time;"
    }
   ]
  },
  {
   "title": "Stateful Pod Count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  coalesce(MAX(apps), 'unknown') AS \"metric\",\n  time,\n  MIN(current) AS \"value\"\nFROM\n(\n  SELECT\n    CONCAT(labels->>'exported_namespace', '/', labels->>'statefulset') AS \"apps\",\n    \"time\" AS \"time\",\n    CASE WHEN name = 'kube_statefulset_status_replicas_ready' THEN value ELSE NULL END AS \"current\"\n  FROM metrics\n  WHERE\n    $__timeFilter(\"time\") and\n    name = 'kube_statefulset_status_replicas_ready' and\n    value != 'NaN'\n) t\nGROUP BY apps, time\nORDER BY apps, time;"
    }
   ]
  },
  {
   "title": "Deployment Pod Count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  coalesce(MAX(apps), 'unknown') AS \"metric\",\n  time,\n  MIN(current) AS \"value\"\nFROM\n(\n  SELECT\n    CONCAT(labels->>'exported_namespace', '/', labels->>'deployment') AS \"apps\",\n    \"time\",\n    value AS \"current\"\n  FROM metrics\n  WHERE\n    $__timeFilter(\"time\") and\n    name = 'kube_deployment_status_replicas_available' and\n    value != 'NaN'\n) t\nGROUP BY apps, time\nORDER BY apps, time;"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Failed Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, metric, value FROM (\nSELECT\n  time,\n  metric,\n  (\n  CASE \n    WHEN lag(value) OVER w IS NULL THEN value\n    ELSE value - lag(value) OVER w\n  END\n  ) AS \"value\"\nFROM (\n  SELECT\n    CONCAT(labels->>'namespace', '/', labels->>'job_name') AS \"metric\",\n    $__timeGroup(\"time\", $__interval),\n    MAX(value) AS \"value\"\n  FROM metrics\n  WHERE\n    $__timeFilter(\"time\") and\n    name = 'kube_job_status_failed' and\n    value > 0\n  GROUP BY time, metric\n) AS m\nWINDOW w AS (PARTITION BY metric ORDER BY time)\nORDER BY time\n) AS t\nWHERE $__timeFilter(\"time\") AND value > 0;\n"
    }
   ]
  },
  {
   "title": "Succeeded Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, metric, value FROM (\nSELECT\n  time,\n  metric,\n  (\n  CASE \n    WHEN lag(value) OVER w IS NULL THEN value\n    ELSE value - lag(value) OVER w\n  END\n  ) AS \"value\"\nFROM (\n  SELECT\n    CONCAT(labels->>'namespace', '/', labels->>'job_name') AS \"metric\",\n    $__timeGroup(\"time\", $__interval),\n    MAX(value) AS \"value\"\n  FROM metrics\n  WHERE\n    $__timeFilter(\"time\") and\n    name = 'kube_job_status_succeeded' and\n    value > 0\n  GROUP BY time, metric\n) AS m\nWINDOW w AS (PARTITION BY metric ORDER BY time)\nORDER BY time\n) AS t\nWHERE $__timeFilter(\"time\") AND value > 0;\n"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Cores",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT metric, value, tg AS \"time\" FROM (\n\nSELECT\n  labels->>'node' AS \"metric\",\n  MAX(value) AS \"value\",\n  $__timeGroup(\"time\", '$__interval') AS \"tg\"\nFROM metrics\nWHERE\n  $__timeFilter(\"time\") and\n  name = 'kube_node_status_capacity_cpu_cores'\nGROUP BY metric, tg\nORDER BY metric, tg\n) AS m"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  labels->>'node' AS \"metric\",\n  \"time\" AS \"time\",\n  value\nFROM metrics\nWHERE\n  $__timeFilter(\"time\") and\n  name = 'kube_node_status_capacity_memory_bytes'\nORDER BY metric, time"
    }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, COUNT(DISTINCT instance) AS \"nodes\" FROM\n(\n  SELECT\n    metrics.labels->>'instance' AS \"instance\",\n    time_bucket('30s',\"time\") AS \"time\",\n    MIN(value) AS \"value\"\n  FROM metrics\n  WHERE\n    $__timeFilter(\"time\")\n    AND name = 'node_uname_info'\n  GROUP BY time, instance\n) t\nGROUP BY time ORDER BY time;"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(labels->>'node', '-', labels->>'condition') AS \"metric\",\n  \"time\" AS \"time\",\n  value\nFROM metrics\nWHERE\n  $__timeFilter(\"time\") and\n  name = 'kube_node_status_condition' and\n  labels->>'status' = 'true'\nORDER BY metric, time"
    }
   ]
  }
 ]
}