FROM timescale/timescaledb:latest-pg11

ENV POSTGRES_DB prometheus

RUN apk add gettext

COPY ./package.json /app/
COPY ./schema /app/schema/
COPY ./scripts /app/scripts/

COPY ./scripts/image-init.sh /docker-entrypoint-initdb.d/