FROM jupyter/scipy-notebook

USER root

ENV PG_MAJOR 11
RUN apt-get update \
    && apt-get install -y gettext-base postgresql-server-dev-$PG_MAJOR \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade jupyterlab-git psycopg2

USER jovyan

RUN jupyter lab build