FROM timescale/timescaledb:latest-pg10

ENV POSTGRES_DB prometheus

RUN apt-get update \
    && apt-get install -y gettext-base \
    && rm -rf /var/lib/apt/lists/*

COPY ./schema /app/schema/
COPY ./scripts /app/scripts/

COPY ./scripts/image-init.sh /docker-entrypoint-initdb.d/