FROM jupyter/scipy-notebook

USER root

ENV PG_MAJOR 10
RUN apt-get update \
    && apt-get install -y postgresql-server-dev-$PG_MAJOR \
    && rm -rf /var/lib/apt/lists/*

RUN pip install psycopg2

USER jovyan